/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package implementaciones;

import java.util.List;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Brian
 */
public class frmVentana extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(frmVentana.class.getName());

    /**
     * Creates new form frmVentana
     */
    public frmVentana() {
        initComponents();
    }

    public void calcular() {
        Calculadora calculadora = new Calculadora();
        String numero = txtNumero.getText();
        int numeroEntero = Integer.parseInt(numero);
        if (txtNumero.getText().length() > 3) {
            lblRespuesta.setFont(lblRespuesta.getFont().deriveFont(14f));
        }
        int respuesta = calculadora.numeroPrimo(numeroEntero);
        if (respuesta == 1) {
            String s1 = numero + " es compuesto! \n";
            String s2 = "Esto debido a que " + numero + " es divisible por: \n";
            List<Integer> divisibles = calculadora.factoresPrimos(numeroEntero);
            //calculadora.factoresPrimos(numeroEntero);
            if(divisibles.size() == 1){
                s2 += divisibles.get(0);
            } else if (divisibles.size() == 2){
                s2 += divisibles.get(0) + " y " + divisibles.get(1);
            } else {
                for (Integer i : divisibles) {
                    if (divisibles.getLast().equals(i)) {
                        s2 += "y " + i + "\n";
                    } else {
                        s2 += i + ", ";
                    }
                }
            }
            String s3 = "Su raíz entera es: " + calculadora.raizEntera(numeroEntero) + "\n";
            String s4 = "Con un residuo de: " + (numeroEntero - (calculadora.raizEntera(numeroEntero) * calculadora.raizEntera(numeroEntero))) + "\n";
            lblRespuesta.setText("<html> <font color='0081fe'>" + s1 + "</font><br><br>" + s2 + "<br><br>" + s3 + "<br><br>" + s4 + "</html>");
            lblRespuesta.revalidate(); // recalcula el tamaño
            lblRespuesta.repaint();    // vuelve a dibujar
        } else {
            String s1 = numero + " es primo! \n";
            String s2 = "Esto debido a que " + numero + " solo es divisible por 1 y sí mismo. \n";
            // igual aqui hay un error xq solo agrega hasta el numero 3
            String s3 = "Números primos anteriores a " + numero + ": \n";
            List<Integer> npa = calculadora.numerosPrimosAnteriores(numeroEntero);
            for (Integer i : npa) {
                if (i > 1100) {
                    JOptionPane.showMessageDialog(frmVentana.this, "Entrada inválida, es un número primo pero es demasiado grande para procesarlo.", "Advertencia!", JOptionPane.WARNING_MESSAGE);
                    return;
                } else if (npa.getLast().equals(i)) {
                    s3 += "y " + i + "\n";
                } else {
                    s3 += i + ", ";
                }
            }
            String s4 = "Su raíz entera es: " + calculadora.raizEntera(numeroEntero) + "\n";
            String s5 = "Con un residuo de: " + (numeroEntero - (calculadora.raizEntera(numeroEntero) * calculadora.raizEntera(numeroEntero))) + "\n";
            lblRespuesta.setText("<html> <font color='1e9900'>" + s1 + "</font><br><br>" + s2 + "<br><br>" + s3 + "<br><br>" + s4 + "<br><br>" + s5 + "</html>");
            lblRespuesta.revalidate(); // recalcula el tamaño
            lblRespuesta.repaint();    // vuelve a dibujar
        }

    }

    public void borrar() {
        txtNumero.setText("");
        lblRespuesta.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblnTexto = new javax.swing.JLabel();
        txtNumero = new javax.swing.JTextField();
        btnBorrar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        lblRespuesta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora Numeros Primos o Compuestos");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblnTexto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblnTexto.setText("Numero:");

        txtNumero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNumeroFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNumeroFocusLost(evt);
            }
        });
        txtNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroActionPerformed(evt);
            }
        });
        txtNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroKeyTyped(evt);
            }
        });

        btnBorrar.setBackground(new java.awt.Color(100, 181, 246));
        btnBorrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnCalcular.setBackground(new java.awt.Color(11, 218, 81));
        btnCalcular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblRespuesta.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(93, Short.MAX_VALUE)
                        .addComponent(lblnTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(61, 61, 61))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRespuesta, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroActionPerformed

    }//GEN-LAST:event_txtNumeroActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        borrar();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void txtNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroKeyTyped
        if (txtNumero.getText().length() >= 4) {
            evt.consume();
        }
    }//GEN-LAST:event_txtNumeroKeyTyped

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        String texto = txtNumero.getText();
        if (texto.matches("\\d+$")) {
            calcular();
        } else {
            JOptionPane.showMessageDialog(frmVentana.this, "Entrada inválida, deben ser números enteros.", "Advertencia!", JOptionPane.WARNING_MESSAGE);
            borrar();
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void txtNumeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFocusGained

    }//GEN-LAST:event_txtNumeroFocusGained

    private void txtNumeroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNumeroFocusLost

    }//GEN-LAST:event_txtNumeroFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new frmVentana().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JLabel lblnTexto;
    private javax.swing.JTextField txtNumero;
    // End of variables declaration//GEN-END:variables
}
